"""empty message

Revision ID: 5cbacaadf160
Revises: 
Create Date: 2021-06-13 11:33:06.319668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbacaadf160'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_dance_oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_user_id', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('provider_user_login', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_flask_dance_oauth_provider'), ['provider', 'provider_user_id'])
        batch_op.create_foreign_key(batch_op.f('fk_flask_dance_oauth_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('provider_username')
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_dance_oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('provider_username', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_flask_dance_oauth_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_flask_dance_oauth_provider'), type_='unique')
        batch_op.drop_column('user_id')
        batch_op.drop_column('provider_user_login')
        batch_op.drop_column('provider_user_id')

    # ### end Alembic commands ###
