"""empty message

Revision ID: f6bb6bee0d3b
Revises: 
Create Date: 2021-07-16 01:40:18.774346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6bb6bee0d3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    with op.batch_alter_table('flask_dance_oauth', schema=None) as batch_op:
        batch_op.drop_constraint('fk_flask_dance_oauth_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_flask_dance_oauth_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_dance_oauth', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_flask_dance_oauth_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_flask_dance_oauth_user_id_users', 'users', ['user_id'], ['id'])

    op.drop_table('user')
    # ### end Alembic commands ###
